[[plugins]]
repo = 'vim-denops/denops.vim'
hook_source = '''
  call jobstart([
    \   'deno', 'run', '-A', '--no-check',
    \   g:dein#plugin.path . '/denops/@denops-private/cli.ts',
    \ ], {'detach': v:true})

  let g:denops_server_addr = '127.0.0.1:32123'
'''

[[plugins]]
repo = 'Shougo/ddx.vim'
hook_add = '''
  nnoremap [Space]x <Cmd>Ddx -path=`'%'->expand()`<CR>
'''
hook_source = '''
  call ddx#custom#patch_global(#{
      \   ui: 'hex',
      \ })
'''
[plugins.ftplugin]
ddx-hex = '''
  nnoremap <buffer> q
  \ <Cmd>call ddx#ui#hex#do_action('quit')<CR>
  nnoremap <buffer> r
  \ <Cmd>call ddx#ui#hex#do_action('change')<CR>
'''

[[plugins]]
repo = 'Shougo/ddx-commands.vim'
depends = 'ddx.vim'
on_cmd = 'Ddx'
