[[plugins]]
repo = 'vim-denops/denops.vim'
hook_source = '''
  "call jobstart([
  "  \   'deno', 'run', '-A', '--no-check',
  "  \   g:dein#plugin.path . '/denops/@denops-private/cli.ts',
  "  \ ], {'detach': v:true})

  "let g:denops_server_addr = '127.0.0.1:32123'
'''
